#####Write a program to understand how the operator precedence works

q=9
w=3
e=6
t=9
y=69

z=((q+w)*e)/t**y
print(z)

name="virat"
age=12

if name=="virat" or name=="alex" and age>=10:
   print("hello wellcome")
else:
   print("kuch aur")

   ####Write to check a number is divisible by another number.

numerator=int(input("enter the numerateor"))
denominator=int(input("enter the numerateor"))

if numerator%denominator==0:
   print("they are divisiable")
else:
   print("they are not divisiable")